#!/usr/bin/env node

import { appendFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REFERENCES = path.join(ROOT, "references");
const INDEX_URL = "https://clerk.com/docs/llms.txt";
const USER_AGENT = "clerk-compendium-sync";
const GENERATED_BANNER =
  "<!-- GENERATED by scripts/sync.mjs from official Clerk sources. Do not edit by hand. -->";

const KNOWN_ROOTS = new Set([
  "android",
  "astro",
  "chrome-extension",
  "cli.md",
  "docs.md",
  "expo",
  "expressjs",
  "fastify",
  "getting-started",
  "go",
  "guides",
  "ios",
  "js-frontend",
  "maintenance-mode.md",
  "nextjs",
  "nuxt",
  "pinning.md",
  "react",
  "react-router",
  "reference",
  "ruby",
  "tanstack-react-start",
  "vue",
]);

const FRAMEWORK_ROOTS = new Map([
  ["android", "Android"],
  ["astro", "Astro"],
  ["chrome-extension", "Chrome Extension"],
  ["expo", "Expo"],
  ["expressjs", "Express"],
  ["fastify", "Fastify"],
  ["go", "Go"],
  ["ios", "iOS"],
  ["js-frontend", "JavaScript"],
  ["nextjs", "Next.js"],
  ["nuxt", "Nuxt"],
  ["react", "React"],
  ["react-router", "React Router"],
  ["ruby", "Ruby"],
  ["tanstack-react-start", "TanStack React Start"],
  ["vue", "Vue"],
]);

const REPOSITORIES = [
  { repo: "clerk/clerk-docs", expectedLicenses: [null] },
  { repo: "clerk/javascript", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-sdk-go", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-sdk-php", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-sdk-python", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-sdk-java", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-sdk-csharp", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-sdk-ruby", expectedLicenses: [null, "Apache-2.0"] },
  { repo: "clerk/clerk-ios", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-android", expectedLicenses: ["MIT"] },
];

const REQUIRED_ANCHORS = [
  {
    key: "nextjs-quickstart",
    path: "/docs/nextjs/getting-started/quickstart.md",
  },
  {
    key: "react-quickstart",
    path: "/docs/react/getting-started/quickstart.md",
  },
  { key: "sessions", path: "/docs/guides/sessions/session-tokens.md" },
  { key: "organizations", path: "/docs/guides/organizations/overview.md" },
  { key: "webhooks", path: "/docs/guides/development/webhooks/overview.md" },
  { key: "billing", path: "/docs/guides/billing/overview.md" },
  { key: "testing", path: "/docs/guides/development/testing/overview.md" },
  {
    key: "environment-variables",
    path: "/docs/guides/development/clerk-environment-variables.md",
  },
];

const CATEGORY_CONFIG = {
  quickstarts: {
    file: "quickstarts.md",
    title: "Clerk Quickstarts",
    useWhen:
      "Use this reference when adding Clerk to a project or repairing framework provider, middleware, request context, or root integration wiring.",
    guidance: [
      "Identify the framework, router mode, runtime, package manager, and installed Clerk package before choosing a quickstart.",
      "Prefer the framework-native first-party package and its current quickstart over generic React or JavaScript setup.",
      "Preserve working provider, middleware, proxy, and route conventions unless the task is an explicit migration.",
      "After setup, verify a public route, a protected server request, a signed-out transition, and a signed-in transition.",
    ],
  },
  "concepts-components": {
    file: "concepts-components.md",
    title: "Clerk Concepts and Components",
    useWhen:
      "Use this reference when choosing Clerk architecture, prebuilt components, custom flows, appearance, localization, or account-management surfaces.",
    guidance: [
      "Choose prebuilt components when their product contract fits. Build a custom flow only when the product needs control the component contract cannot provide.",
      "Treat Clerk frontend state as presentation and interaction state. Server authorization still owns access decisions.",
      "Keep provider configuration centralized and preserve framework rendering boundaries.",
      "Localize Clerk's vocabulary when the product uses different user-facing terms, and verify every mounted Clerk surface.",
    ],
  },
  "auth-sessions": {
    file: "auth-sessions.md",
    title: "Clerk Authentication and Sessions",
    useWhen:
      "Use this reference for sign-in, sign-up, sessions, tokens, claims, MFA, passkeys, social connections, reverification, or machine authentication.",
    guidance: [
      "Authentication proves identity. It does not prove authorization to a route, organization, or resource.",
      "Use the framework's server helper to derive trusted session state. Do not authorize from a client-provided user identifier or token payload that was not verified.",
      "Keep session claims small and use them only when their freshness contract fits the decision.",
      "Treat machine identities as a separate trust path with explicit audience, scope, rotation, and revocation behavior.",
    ],
  },
  "users-organizations": {
    file: "users-organizations.md",
    title: "Clerk Users and Organizations",
    useWhen:
      "Use this reference for users, metadata, organizations, memberships, invitations, active organization context, domains, roles, or permissions.",
    guidance: [
      "Derive organization membership and permissions from verified Clerk state at the server boundary.",
      "An active organization selection is navigation context, not proof that the user may access every resource associated with that organization.",
      "Store application-owned data in the application database and keep one declared owner for each fact synchronized from Clerk.",
      "Design invitation and membership transitions for retries, revocation, expired links, and users who belong to several organizations.",
    ],
  },
  billing: {
    file: "billing.md",
    title: "Clerk Billing",
    useWhen:
      "Use this reference for Clerk plans, features, subscriptions, trials, entitlements, Billing components, Billing webhooks, or server-side feature gates.",
    guidance: [
      "Determine whether the subscription owner is a user or organization before modeling entitlement checks.",
      "Enforce paid features at the server boundary. A hidden component or client-side feature check is not an entitlement gate.",
      "Treat subscription state as provider-owned and application access rules as application-owned.",
      "Test upgrades, downgrades, cancellation, trial expiration, delayed webhooks, and temporary provider failure.",
    ],
  },
  security: {
    file: "security.md",
    title: "Clerk Security",
    useWhen:
      "Use this reference when protecting routes or resources, reviewing trust boundaries, rotating keys, preventing abuse, or validating security posture.",
    guidance: [
      "Keep secret keys, webhook secrets, and privileged Backend API calls in server-only runtimes.",
      "Apply authorization where the protected operation executes, even when middleware also filters requests.",
      "Fail closed when verified session, organization, permission, ownership, or entitlement state is absent.",
      "Rotate credentials by stage and verify old credentials are retired after callers have moved.",
    ],
  },
  "integrations-databases": {
    file: "integrations-databases.md",
    title: "Clerk Integrations and Databases",
    useWhen:
      "Use this reference for webhooks, database synchronization, external backends, OAuth integrations, or third-party services.",
    guidance: [
      "Verify a webhook signature against the raw request body before parsing or trusting payload fields.",
      "Make event handling idempotent, transactional where needed, and tolerant of duplicate, delayed, and out-of-order delivery.",
      "Use event identifiers and source versions to prevent an older event from overwriting newer application state.",
      "Define which Clerk facts are mirrored, why they are needed, and how the application recovers after missed events.",
    ],
  },
  operations: {
    file: "operations.md",
    title: "Clerk Operations",
    useWhen:
      "Use this reference for environment variables, instances, domains, redirects, deployment, testing, troubleshooting, Dashboard configuration, or SDK upgrades.",
    guidance: [
      "Keep development and production instances separate, with the same environment key names and stage-specific values.",
      "Verify allowed origins, redirect URLs, domains, webhook endpoints, and credentials in the provider dashboard as part of runtime completion.",
      "Use testing tokens and provider-supported test paths instead of weakening production security controls for automation.",
      "During upgrades, inspect installed versions and migration guidance, then validate both browser flow and protected server behavior.",
    ],
  },
  "sdk-api": {
    file: "sdk-api.md",
    title: "Clerk SDK and API Reference",
    useWhen:
      "Use this reference for exact packages, imports, helpers, methods, types, Backend API resources, Frontend API resources, or Platform API resources.",
    guidance: [
      "Check the target project's installed SDK version and exports before using a symbol from current documentation.",
      "Prefer a released first-party SDK over direct HTTP calls when the SDK supports the required operation and runtime.",
      "Treat default-branch source as discovery evidence, not proof that a symbol exists in a released package.",
      "Use the complete source index when an exact method, type, object, or resource is not listed in this focused reference.",
    ],
  },
};

const TAG_RULES = [
  ["authentication", /auth|sign-in|sign-up|login|logout|password|passkey/i],
  ["sessions", /session|token|jwt|claim/i],
  [
    "organizations",
    /organization|membership|invitation|domain|role|permission/i,
  ],
  ["billing", /billing|subscription|plan|feature|entitlement|trial/i],
  ["webhooks", /webhook|event/i],
  ["testing", /test|playwright|cypress/i],
  ["deployment", /deploy|production|environment|domain|redirect|origin/i],
  [
    "security",
    /security|protect|authorization|restrict|rotation|reverification/i,
  ],
  [
    "components",
    /component|appearance|localization|custom flow|account portal/i,
  ],
  ["api", /api|sdk|reference|method|object/i],
];

function printHelp() {
  console.log(`Usage: node scripts/sync.mjs [--check] [--help]

Discovers Clerk's first-party documentation and official SDK repositories, then
renders references/ without copying Clerk documentation prose. Requires Node 18+
and network access to clerk.com, api.github.com, and raw.githubusercontent.com.
Set GITHUB_TOKEN to raise GitHub API rate limits.

  --check  Compare generated output with disk without writing
  --help   Show this help

Generated references are deterministic. The script never edits SKILL.md or its
metadata.version.`);
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

async function fetchResponse(url, options = {}) {
  const response = await fetch(url, {
    redirect: "follow",
    ...options,
    headers: {
      "User-Agent": USER_AGENT,
      ...options.headers,
    },
  });
  if (!response.ok) {
    const detail = (await response.text()).slice(0, 500).replace(/\s+/g, " ");
    throw new Error(
      `GET ${url} returned ${response.status} ${response.statusText}${detail ? `: ${detail}` : ""}`,
    );
  }
  return response;
}

async function fetchText(url, expectedHosts) {
  const response = await fetchResponse(url);
  const finalUrl = new URL(response.url);
  if (expectedHosts && !expectedHosts.has(finalUrl.hostname)) {
    throw new Error(
      `GET ${url} redirected to unexpected host ${finalUrl.hostname}`,
    );
  }
  return response.text();
}

async function fetchJson(url) {
  const response = await fetchResponse(url, {
    headers: {
      Accept: "application/vnd.github+json",
      ...(process.env.GITHUB_TOKEN
        ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` }
        : {}),
    },
  });
  return response.json();
}

function normalizeDocUrl(value) {
  const url = new URL(value);
  if (url.protocol !== "https:" || url.hostname !== "clerk.com") {
    throw new Error(`Unexpected Clerk documentation URL: ${value}`);
  }
  if (
    (url.pathname !== "/docs.md" && !url.pathname.startsWith("/docs/")) ||
    !url.pathname.endsWith(".md")
  ) {
    throw new Error(`Unexpected Clerk documentation path: ${value}`);
  }
  url.hash = "";
  url.search = "";
  return url.toString();
}

function parseIndex(text) {
  const linkPattern = /^\s*-\s+\[([^\]]+)]\(([^)]+)\)(?::\s*.*)?$/gm;
  const documents = [];
  const seen = new Map();
  let indexedLinks = 0;
  for (const match of text.matchAll(linkPattern)) {
    indexedLinks += 1;
    const title = match[1].trim();
    const url = normalizeDocUrl(match[2]);
    const previous = seen.get(url);
    if (previous && previous !== title) {
      throw new Error(
        `Clerk index gives ${url} conflicting titles: ${previous} and ${title}`,
      );
    }
    if (!previous) {
      seen.set(url, title);
      documents.push({ title, url });
    }
  }
  if (indexedLinks < 2000 || documents.length < 2000) {
    throw new Error(
      `Clerk index yielded only ${indexedLinks} links and ${documents.length} unique documents, expected at least 2000`,
    );
  }
  return documents;
}

function rootFor(document) {
  const pathname = new URL(document.url).pathname;
  if (pathname === "/docs.md") return "docs.md";
  return pathname.replace(/^\/docs\//, "").split("/")[0];
}

function classify(document) {
  const url = new URL(document.url);
  const root = rootFor(document);
  const pathText = url.pathname.toLowerCase();
  const text = `${document.title} ${pathText}`.toLowerCase();

  if (!KNOWN_ROOTS.has(root)) {
    throw new Error(
      `Unclassified Clerk documentation root: ${root} (${document.url})`,
    );
  }

  if (
    root === "getting-started" ||
    /quickstart|quick-start|setup-clerk|install-clerk/.test(text)
  ) {
    return "quickstarts";
  }
  if (
    /billing|subscription|entitlement|pricing-plan|checkout|payment-attempt/.test(
      text,
    )
  ) {
    return "billing";
  }
  if (
    /organization|membership|invitation|enterprise-connection|verified-domain|role|permission/.test(
      text,
    )
  ) {
    return "users-organizations";
  }
  if (
    /webhook|database|integration|sync(ing)?-user|oauth-application|convex|supabase|firebase/.test(
      text,
    )
  ) {
    return "integrations-databases";
  }
  if (
    /security|authorization|protect|restrict|bot|key-rotation|reverification|lockout|enumeration/.test(
      text,
    )
  ) {
    return "security";
  }
  if (
    /sign-in|sign-up|authentication|session|token|jwt|claim|password|passkey|mfa|multi-factor|machine|m2m|api-key|social-connection|web3/.test(
      text,
    )
  ) {
    return "auth-sessions";
  }
  if (
    /deploy|environment|troubleshoot|testing|test-|playwright|cypress|upgrade|migrat|dashboard|(?:^|[\/-])cli(?:[\/. -]|$)|maintenance|domain|redirect|origin|error/.test(
      text,
    )
  ) {
    return "operations";
  }
  if (
    root === "reference" ||
    /api-reference|sdk-reference|backend-api|frontend-api|platform-api|types?\//.test(
      text,
    )
  ) {
    return "sdk-api";
  }
  return "concepts-components";
}

function inferKind(document) {
  const text = `${document.title} ${document.url}`.toLowerCase();
  if (/quickstart|quick-start/.test(text)) return "quickstart";
  if (/api-reference|sdk-reference|\/reference\//.test(text))
    return "reference";
  if (/component/.test(text)) return "component";
  if (/upgrade|migration|migrate/.test(text)) return "migration";
  if (/troubleshoot|error/.test(text)) return "troubleshooting";
  if (/overview|introduction|architecture/.test(text)) return "concept";
  return "guide";
}

function inferTags(document) {
  const text = `${document.title} ${document.url}`;
  return TAG_RULES.filter(([, pattern]) => pattern.test(text)).map(
    ([tag]) => tag,
  );
}

function enrichDocuments(documents) {
  return documents
    .map((document) => {
      const root = rootFor(document);
      return {
        title: document.title,
        url: document.url,
        primaryCategory: classify(document),
        tags: inferTags(document),
        framework: FRAMEWORK_ROOTS.get(root) ?? null,
        kind: inferKind(document),
        deprecated: /deprecated|legacy|previous version|old version/i.test(
          `${document.title} ${document.url}`,
        ),
      };
    })
    .sort((a, b) => a.url.localeCompare(b.url));
}

async function inspectRepository(config) {
  const metadata = await fetchJson(
    `https://api.github.com/repos/${config.repo}`,
  );
  const license = metadata.license?.spdx_id ?? null;
  if (!config.expectedLicenses.includes(license)) {
    throw new Error(
      `${config.repo} license changed to ${license ?? "unlicensed"}, expected ${config.expectedLicenses.map((value) => value ?? "unlicensed").join(" or ")}`,
    );
  }
  const commit = await fetchJson(
    `https://api.github.com/repos/${config.repo}/commits/${metadata.default_branch}`,
  );
  return {
    name: config.repo,
    url: metadata.html_url,
    defaultBranch: metadata.default_branch,
    license,
    sha: commit.sha,
  };
}

async function inspectRepositories() {
  const repositories = [];
  for (const config of REPOSITORIES) {
    repositories.push(await inspectRepository(config));
  }
  return repositories.sort((a, b) => a.name.localeCompare(b.name));
}

async function inspectJavaScriptPackages(repository) {
  const contents = await fetchJson(
    `https://api.github.com/repos/clerk/javascript/contents/packages?ref=${repository.sha}`,
  );
  const directories = contents
    .filter((entry) => entry.type === "dir")
    .map((entry) => entry.name)
    .sort();
  const packages = [];
  for (const directory of directories) {
    const rawUrl = `https://raw.githubusercontent.com/clerk/javascript/${repository.sha}/packages/${directory}/package.json`;
    let manifest;
    try {
      manifest = JSON.parse(
        await fetchText(rawUrl, new Set(["raw.githubusercontent.com"])),
      );
    } catch (error) {
      if (String(error).includes("returned 404")) continue;
      throw error;
    }
    if (
      manifest.private !== true &&
      typeof manifest.name === "string" &&
      manifest.name.startsWith("@clerk/")
    ) {
      packages.push({
        name: manifest.name,
        directory: `packages/${directory}`,
        repository: "clerk/javascript",
      });
    }
  }
  if (packages.length < 15) {
    throw new Error(
      `Found only ${packages.length} @clerk packages in clerk/javascript`,
    );
  }
  return packages.sort((a, b) => a.name.localeCompare(b.name));
}

function selectAnchor(anchor, documents) {
  const document = documents.find(
    (candidate) => new URL(candidate.url).pathname === anchor.path,
  );
  if (!document) {
    throw new Error(
      `Required Clerk documentation anchor disappeared: ${anchor.key} (${anchor.path})`,
    );
  }
  return document;
}

async function hashAnchors(documents) {
  const anchors = [];
  for (const requirement of REQUIRED_ANCHORS) {
    const document = selectAnchor(requirement, documents);
    const body = await fetchText(document.url, new Set(["clerk.com"]));
    anchors.push({
      key: requirement.key,
      title: document.title,
      url: document.url,
      sha256: sha256(body),
    });
  }
  return anchors.sort((a, b) => a.key.localeCompare(b.key));
}

function countBy(items, selector) {
  const counts = new Map();
  for (const item of items) {
    const key = selector(item);
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return Object.fromEntries([...counts].sort(([a], [b]) => a.localeCompare(b)));
}

function selectCategorySources(category, documents) {
  const categoryDocuments = documents.filter(
    (document) => document.primaryCategory === category,
  );
  const selected = [];
  const seen = new Set();

  for (const framework of [
    ...new Set(categoryDocuments.map((item) => item.framework).filter(Boolean)),
  ].sort()) {
    const match = categoryDocuments.find(
      (document) => document.framework === framework,
    );
    if (match && !seen.has(match.url)) {
      selected.push(match);
      seen.add(match.url);
    }
  }

  const scored = categoryDocuments
    .map((document) => {
      const text = `${document.title} ${document.url}`.toLowerCase();
      let score = 0;
      if (document.kind === "quickstart") score += 8;
      if (document.kind === "concept") score += 5;
      if (
        /overview|introduction|custom|protect|verify|setup|configure/.test(text)
      )
        score += 4;
      if (/deprecated|legacy/.test(text)) score -= 8;
      score -= new URL(document.url).pathname.split("/").length * 0.1;
      return { document, score };
    })
    .sort(
      (a, b) =>
        b.score - a.score || a.document.title.localeCompare(b.document.title),
    );

  for (const { document } of scored) {
    if (selected.length >= 60) break;
    if (!seen.has(document.url)) {
      selected.push(document);
      seen.add(document.url);
    }
  }
  return selected.sort((a, b) => {
    const frameworkCompare = (a.framework ?? "").localeCompare(
      b.framework ?? "",
    );
    return (
      frameworkCompare ||
      a.title.localeCompare(b.title) ||
      a.url.localeCompare(b.url)
    );
  });
}

function renderRepositoryTable(repositories) {
  const lines = [
    "| Repository | Default branch | License |",
    "| --- | --- | --- |",
  ];
  for (const repository of repositories) {
    lines.push(
      `| [${repository.name}](${repository.url}) | \`${repository.defaultBranch}\` | ${repository.license ?? "No explicit repository license detected"} |`,
    );
  }
  return lines.join("\n");
}

function renderPackageTable(packages) {
  const lines = ["| Package | Source directory |", "| --- | --- |"];
  for (const item of packages) {
    lines.push(
      `| \`${item.name}\` | [\`${item.directory}\`](https://github.com/clerk/javascript/tree/main/${item.directory}) |`,
    );
  }
  return lines.join("\n");
}

function renderReference(category, documents, repositories, packages) {
  const config = CATEGORY_CONFIG[category];
  const selected = selectCategorySources(category, documents);
  const categoryCount = documents.filter(
    (document) => document.primaryCategory === category,
  ).length;
  const lines = [
    GENERATED_BANNER,
    "",
    `# ${config.title}`,
    "",
    `_Discovery source: [Clerk's language-model documentation index](${INDEX_URL})_`,
    "",
    config.useWhen,
    "",
    "## Operating Guidance",
    "",
    ...config.guidance.map((item) => `- ${item}`),
    "",
  ];

  if (category === "sdk-api") {
    lines.push(
      "## Official SDK Repositories",
      "",
      renderRepositoryTable(repositories),
      "",
      "## JavaScript Packages",
      "",
      renderPackageTable(packages),
      "",
    );
  }

  lines.push(
    "## Selected Official Sources",
    "",
    `This focused list selects ${selected.length} of ${categoryCount} current documents in this category. Search [source-index.json](source-index.json) when the exact method, object, framework page, or resource is not listed.`,
    "",
  );

  let currentFramework = null;
  for (const document of selected) {
    const framework = document.framework ?? "Cross-framework";
    if (framework !== currentFramework) {
      if (currentFramework !== null) lines.push("");
      lines.push(`### ${framework}`, "");
      currentFramework = framework;
    }
    const markers = [document.kind, ...document.tags.slice(0, 3)];
    lines.push(
      `- [${document.title}](${document.url}) (${markers.join(", ")})`,
    );
  }

  return `${lines.join("\n").trim()}\n`;
}

function publicRepository(repository) {
  return {
    name: repository.name,
    url: repository.url,
    defaultBranch: repository.defaultBranch,
    license: repository.license,
  };
}

function renderIndex(indexHash, documents, repositories, packages, anchors) {
  return `${JSON.stringify(
    {
      generated: true,
      discoverySource: INDEX_URL,
      discoverySha256: indexHash,
      counts: {
        documents: documents.length,
        categories: countBy(documents, (document) => document.primaryCategory),
        frameworks: countBy(
          documents.filter((document) => document.framework),
          (document) => document.framework,
        ),
        packages: packages.length,
        repositories: repositories.length,
      },
      repositories: repositories.map(publicRepository),
      packages,
      anchors,
      documents,
    },
    null,
    2,
  )}\n`;
}

async function readPreviousIndex() {
  try {
    return JSON.parse(
      await readFile(path.join(REFERENCES, "source-index.json"), "utf8"),
    );
  } catch (error) {
    if (error?.code === "ENOENT") return null;
    throw new Error(
      `Could not read previous source-index.json: ${error.message}`,
    );
  }
}

function mapBy(items, key) {
  return new Map((items ?? []).map((item) => [item[key], item]));
}

function reportSetDiff(label, before, after) {
  const oldSet = new Set(before);
  const newSet = new Set(after);
  const added = [...newSet].filter((value) => !oldSet.has(value)).sort();
  const removed = [...oldSet].filter((value) => !newSet.has(value)).sort();
  if (added.length > 0) {
    console.log(`${label} added (${added.length}):`);
    for (const value of added) console.log(`  + ${value}`);
  }
  if (removed.length > 0) {
    console.log(`${label} removed (${removed.length}):`);
    for (const value of removed) console.log(`  - ${value}`);
  }
}

function reportDrift(previous, current) {
  if (!previous) {
    console.log("No previous source index. This is the initial generation.");
    return;
  }
  reportSetDiff(
    "Documents",
    previous.documents?.map((item) => item.url) ?? [],
    current.documents.map((item) => item.url),
  );
  reportSetDiff(
    "Packages",
    previous.packages?.map((item) => item.name) ?? [],
    current.packages.map((item) => item.name),
  );
  reportSetDiff(
    "Repositories",
    previous.repositories?.map((item) => item.name) ?? [],
    current.repositories.map((item) => item.name),
  );

  const oldDocuments = mapBy(previous.documents, "url");
  for (const document of current.documents) {
    const old = oldDocuments.get(document.url);
    if (old && old.primaryCategory !== document.primaryCategory) {
      console.log(
        `Category changed: ${document.url} (${old.primaryCategory} -> ${document.primaryCategory})`,
      );
    }
    if (old && old.deprecated !== document.deprecated) {
      console.log(
        `Deprecation changed: ${document.url} (${old.deprecated} -> ${document.deprecated})`,
      );
    }
  }

  const oldTitleCounts = countBy(
    previous.documents ?? [],
    (item) => item.title,
  );
  const newTitleCounts = countBy(current.documents, (item) => item.title);
  const oldByTitle = mapBy(previous.documents, "title");
  for (const document of current.documents) {
    const old = oldByTitle.get(document.title);
    if (
      old &&
      old.url !== document.url &&
      oldTitleCounts[document.title] === 1 &&
      newTitleCounts[document.title] === 1
    ) {
      console.log(
        `Possible move: ${document.title} (${old.url} -> ${document.url})`,
      );
    }
  }

  const oldAnchors = mapBy(previous.anchors, "key");
  for (const anchor of current.anchors) {
    const old = oldAnchors.get(anchor.key);
    if (old && old.sha256 !== anchor.sha256) {
      console.log(`Anchor changed: ${anchor.key} (${anchor.url})`);
    }
  }

  const oldRepositories = mapBy(previous.repositories, "name");
  for (const repository of current.repositories) {
    const old = oldRepositories.get(repository.name);
    if (old && old.license !== repository.license) {
      console.log(
        `Repository license changed: ${repository.name} (${old.license ?? "unlicensed"} -> ${repository.license ?? "unlicensed"})`,
      );
    }
  }
}

async function writeOutputs(outputs, checkOnly) {
  const changed = [];
  for (const [relativePath, content] of outputs) {
    const destination = path.join(ROOT, relativePath);
    let existing = null;
    try {
      existing = await readFile(destination, "utf8");
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
    if (existing !== content) changed.push(relativePath);
  }

  if (checkOnly) {
    if (changed.length > 0) {
      for (const file of changed) console.error(`out of date: ${file}`);
      process.exitCode = 1;
    } else {
      console.log("Generated Clerk references are current.");
    }
    return;
  }

  await mkdir(REFERENCES, { recursive: true });
  for (const [relativePath, content] of outputs) {
    await writeFile(path.join(ROOT, relativePath), content, "utf8");
    console.log(`wrote ${relativePath}`);
  }
}

async function exportOutputs(repositories, indexHash) {
  if (!process.env.GITHUB_OUTPUT) return;
  const entries = [
    ["llms_sha256", indexHash],
    ...repositories.map((repository) => [
      `${repository.name.replace(/[^a-z0-9]+/gi, "_").toLowerCase()}_sha`,
      repository.sha,
    ]),
  ];
  await appendFile(
    process.env.GITHUB_OUTPUT,
    entries.map(([key, value]) => `${key}=${value}`).join("\n") + "\n",
  );
}

async function main() {
  const args = new Set(process.argv.slice(2));
  if (args.has("--help") || args.has("-h")) {
    printHelp();
    return;
  }
  const allowed = new Set(["--check"]);
  for (const argument of args) {
    if (!allowed.has(argument))
      throw new Error(`Unknown argument: ${argument}`);
  }
  const checkOnly = args.has("--check");

  const indexText = await fetchText(INDEX_URL, new Set(["clerk.com"]));
  const parsed = parseIndex(indexText);
  const documents = enrichDocuments(parsed);
  const roots = new Set(documents.map(rootFor));
  const unknownRoots = [...roots].filter((root) => !KNOWN_ROOTS.has(root));
  if (unknownRoots.length > 0) {
    throw new Error(
      `Unknown Clerk documentation roots: ${unknownRoots.join(", ")}`,
    );
  }

  const repositories = await inspectRepositories();
  const javascript = repositories.find(
    (repository) => repository.name === "clerk/javascript",
  );
  const packages = await inspectJavaScriptPackages(javascript);
  const anchors = await hashAnchors(documents);
  const indexHash = sha256(indexText);

  const publicIndex = {
    repositories: repositories.map(publicRepository),
    packages,
    anchors,
    documents,
  };
  const previous = await readPreviousIndex();
  reportDrift(previous, publicIndex);

  const outputs = new Map();
  for (const category of Object.keys(CATEGORY_CONFIG)) {
    const file = CATEGORY_CONFIG[category].file;
    outputs.set(
      `references/${file}`,
      renderReference(category, documents, repositories, packages),
    );
  }
  outputs.set(
    "references/source-index.json",
    renderIndex(indexHash, documents, repositories, packages, anchors),
  );

  await writeOutputs(outputs, checkOnly);
  console.log(
    `indexed ${documents.length} Clerk documents, ${packages.length} JavaScript packages, and ${repositories.length} repositories`,
  );
  for (const repository of repositories) {
    console.log(`upstream ${repository.name} @ ${repository.sha}`);
  }
  console.log(`upstream llms.txt sha256 ${indexHash}`);
  await exportOutputs(repositories, indexHash);
}

main().catch((error) => {
  console.error(error.stack ?? error.message ?? String(error));
  process.exit(1);
});
