#!/usr/bin/env node

import {
  appendFile,
  mkdir,
  readdir,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REFERENCES = path.join(ROOT, "references");
const INDEX_URL = "https://clerk.com/docs/llms.txt";
const USER_AGENT = "clerk-compendium-sync";
const GENERATED_BANNER =
  "<!-- GENERATED by scripts/sync.mjs from official Clerk sources. Do not edit by hand. -->";
const DOCS_URL = "https://clerk.com/docs/";
const SOURCES_HEADING = "## Official Sources";
const TOP_LEVEL_AREA = "Top Level";
const ALL_FRAMEWORKS_AREA = "All Frameworks";
const AREA_LIMIT = 12;
const AREA_MINIMUM = 3;
const STATE_FILE = "scripts/sync-state.json";

const KNOWN_ROOTS = new Set([
  "android",
  "astro",
  "chrome-extension",
  "cli.md",
  "docs.md",
  "electron",
  "expo",
  "expressjs",
  "fastify",
  "getting-started",
  "go",
  "guides",
  "ios",
  "js-frontend",
  "maintenance-mode.md",
  "nextjs",
  "nuxt",
  "pinning.md",
  "react",
  "react-router",
  "reference",
  "ruby",
  "tanstack-react-start",
  "templates.md",
  "vue",
]);

const FRAMEWORK_ROOTS = new Set([
  "android",
  "astro",
  "chrome-extension",
  "electron",
  "expo",
  "expressjs",
  "fastify",
  "go",
  "ios",
  "js-frontend",
  "nextjs",
  "nuxt",
  "react",
  "react-router",
  "ruby",
  "tanstack-react-start",
  "vue",
]);

const REFERENCE_FOLDERS = new Map([
  ["backend", "backend-reference"],
  ["components", "component-reference"],
  ["native-components", "component-reference"],
  ["views", "component-reference"],
  ["client-side-helpers", "hook-reference"],
  ["composables", "hook-reference"],
  ["hooks", "hook-reference"],
  ["native-hooks", "hook-reference"],
  ["objects", "object-type-reference"],
  ["types", "object-type-reference"],
]);

const REPOSITORIES = [
  { repo: "clerk/clerk-docs", expectedLicenses: [null] },
  { repo: "clerk/javascript", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-sdk-go", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-sdk-php", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-sdk-python", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-sdk-java", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-sdk-csharp", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-sdk-ruby", expectedLicenses: [null, "Apache-2.0"] },
  { repo: "clerk/clerk-ios", expectedLicenses: ["MIT"] },
  { repo: "clerk/clerk-android", expectedLicenses: ["MIT"] },
];

const REQUIRED_ANCHORS = [
  {
    key: "nextjs-quickstart",
    path: "/docs/nextjs/getting-started/quickstart.md",
  },
  {
    key: "react-quickstart",
    path: "/docs/react/getting-started/quickstart.md",
  },
  { key: "sessions", path: "/docs/guides/sessions/session-tokens.md" },
  { key: "organizations", path: "/docs/guides/organizations/overview.md" },
  { key: "webhooks", path: "/docs/guides/development/webhooks/overview.md" },
  { key: "billing", path: "/docs/guides/billing/overview.md" },
  { key: "testing", path: "/docs/guides/development/testing/overview.md" },
  {
    key: "environment-variables",
    path: "/docs/guides/development/clerk-environment-variables.md",
  },
];

const CATEGORY_CONFIG = {
  quickstarts: {
    file: "quickstarts.md",
    title: "Clerk Quickstarts",
    useWhen:
      "Use this reference when adding Clerk to a project, repairing framework provider, middleware, request context, or root integration wiring, or looking for a Clerk-maintained starter, demo, or example repository.",
    guidance: [
      "Identify the framework, router mode, runtime, package manager, and installed Clerk package before choosing a quickstart.",
      "Prefer the framework-native first-party package and its current quickstart over generic React or JavaScript setup.",
      "Preserve working provider, middleware, proxy, and route conventions unless the task is an explicit migration.",
      "After setup, verify a public route, a protected server request, a signed-out transition, and a signed-in transition.",
    ],
  },
  "concepts-components": {
    file: "concepts-components.md",
    title: "Clerk Concepts and Components",
    useWhen:
      "Use this reference when choosing Clerk architecture, prebuilt components, custom flows, appearance, localization, or account-management surfaces.",
    guidance: [
      "Choose prebuilt components when their product contract fits. Build a custom flow only when the product needs control the component contract cannot provide.",
      "Treat Clerk frontend state as presentation and interaction state. Server authorization still owns access decisions.",
      "Keep provider configuration centralized and preserve framework rendering boundaries.",
      "Localize Clerk's vocabulary when the product uses different user-facing terms, and verify every mounted Clerk surface.",
    ],
  },
  "auth-sessions": {
    file: "auth-sessions.md",
    title: "Clerk Authentication and Sessions",
    useWhen:
      "Use this reference for sign-in, sign-up, sessions, tokens, claims, MFA, passkeys, social connections, or machine authentication.",
    guidance: [
      "Treat machine identities as a separate trust path with explicit audience, scope, rotation, and revocation behavior.",
    ],
  },
  "users-organizations": {
    file: "users-organizations.md",
    title: "Clerk Users and Organizations",
    useWhen:
      "Use this reference for users, metadata, organizations, memberships, invitations, active organization context, domains, enterprise SSO connections, roles, or permissions.",
    guidance: [
      "An active organization selection is navigation context, not proof that the user may access every resource associated with that organization.",
      "Store application-owned data in the application database and keep one declared owner for each fact synchronized from Clerk.",
      "Design invitation and membership transitions for retries, revocation, expired links, and users who belong to several organizations.",
    ],
  },
  billing: {
    file: "billing.md",
    title: "Clerk Billing",
    useWhen:
      "Use this reference for Clerk plans, features, subscriptions, trials, entitlements, Billing components, Billing webhooks, or server-side feature gates.",
    guidance: [
      "Determine whether the subscription owner is a user or organization before modeling entitlement checks.",
      "Treat subscription state as provider-owned and application access rules as application-owned.",
      "Test upgrades, downgrades, cancellation, trial expiration, delayed webhooks, and temporary provider failure.",
    ],
  },
  security: {
    file: "security.md",
    title: "Clerk Security",
    useWhen:
      "Use this reference when protecting routes or resources, reviewing trust boundaries, adding reverification, rotating keys, preventing abuse, or validating security posture.",
    guidance: [
      "Rotate credentials by stage and verify old credentials are retired after callers have moved.",
    ],
  },
  "integrations-databases": {
    file: "integrations-databases.md",
    title: "Clerk Integrations and Databases",
    useWhen:
      "Use this reference for webhooks, database synchronization, external backends, Clerk as an OAuth or OIDC provider, or third-party services.",
    guidance: [
      "Make event handling idempotent, transactional where needed, and tolerant of duplicate, delayed, and out-of-order delivery.",
      "Use the delivery identifier to skip repeated events, and compare update or event times so an older event cannot overwrite newer application state or recreate a deleted record.",
      "Define which Clerk facts are mirrored, why they are needed, and how the application recovers after missed events.",
    ],
  },
  operations: {
    file: "operations.md",
    title: "Clerk Operations",
    useWhen:
      "Use this reference for environment variables, instances, domains, redirects, deployment, testing, troubleshooting, Dashboard configuration, or SDK upgrades.",
    guidance: [
      "Keep development and production instances separate, with the same environment key names and stage-specific values.",
      "Verify allowed origins, redirect URLs, domains, webhook endpoints, and credentials in the provider dashboard as part of runtime completion.",
      "Use testing tokens and provider-supported test paths instead of weakening production security controls for automation.",
      "During upgrades, inspect installed versions and migration guidance, then validate both browser flow and protected server behavior.",
    ],
  },
  "backend-reference": {
    file: "backend-reference.md",
    title: "Clerk Backend SDK Reference",
    useWhen:
      "Use this reference for a Backend SDK method or a Backend object, when the exact name, parameters, or returned shape matters.",
    guidance: [
      "A method page sits in the folder of its resource, such as `user` or `organization`, and Backend object pages sit in `types`.",
    ],
  },
  "component-reference": {
    file: "component-reference.md",
    title: "Clerk Component Reference",
    useWhen:
      "Use this reference for the props and usage of a prebuilt Clerk component, a control component, or a native view.",
    guidance: [
      "Open the page under the target project's framework root, because props and imports differ between SDKs.",
    ],
  },
  "hook-reference": {
    file: "hook-reference.md",
    title: "Clerk Hook and Composable Reference",
    useWhen:
      "Use this reference for a React hook, a Vue or Nuxt composable, an Expo native hook, or an Astro client-side store.",
    guidance: [
      "The roots named after an entry are the SDKs that document it. Confirm the target project's root is among them before importing.",
    ],
  },
  "object-type-reference": {
    file: "object-type-reference.md",
    title: "Clerk Object and Type Reference",
    useWhen:
      "Use this reference for the shape of a Clerk frontend object or of a type that an SDK exports.",
    guidance: [
      "Read the page under the target project's framework root, then confirm the shape against the installed package's types.",
    ],
  },
  "sdk-api": {
    file: "sdk-api.md",
    title: "Clerk SDK and API Reference",
    byRoot: true,
    useWhen:
      "Use this reference for exact packages, official repositories, and what one framework SDK documents for itself: its overview, middleware, server helpers, error pages, passkey setup, and the native Android and iOS SDK pages.",
    guidance: [
      "Check the target project's installed SDK version and exports before using a symbol from current documentation.",
      "Prefer a released first-party SDK over direct HTTP calls when the SDK supports the required operation and runtime.",
      "Treat default-branch source as discovery evidence, not proof that a symbol exists in a released package.",
    ],
  },
};

function printHelp() {
  console.log(`Usage: node scripts/sync.mjs [--check] [--help]

Discovers Clerk's first-party documentation and official SDK repositories, then
renders references/ without copying Clerk documentation prose. Requires Node 18+
and network access to clerk.com, api.github.com, and raw.githubusercontent.com.
Set GITHUB_TOKEN to raise GitHub API rate limits.

  --check  Compare generated output with disk without writing
  --help   Show this help

Generated references are deterministic. The script never edits SKILL.md or its
metadata.version.`);
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

async function fetchResponse(url, options = {}) {
  const response = await fetch(url, {
    redirect: "follow",
    ...options,
    headers: {
      "User-Agent": USER_AGENT,
      ...options.headers,
    },
  });
  if (!response.ok) {
    const detail = (await response.text()).slice(0, 500).replace(/\s+/g, " ");
    throw new Error(
      `GET ${url} returned ${response.status} ${response.statusText}${detail ? `: ${detail}` : ""}`,
    );
  }
  return response;
}

async function fetchText(url, expectedHosts) {
  const response = await fetchResponse(url);
  const finalUrl = new URL(response.url);
  if (expectedHosts && !expectedHosts.has(finalUrl.hostname)) {
    throw new Error(
      `GET ${url} redirected to unexpected host ${finalUrl.hostname}`,
    );
  }
  return response.text();
}

async function fetchJson(url) {
  const response = await fetchResponse(url, {
    headers: {
      Accept: "application/vnd.github+json",
      ...(process.env.GITHUB_TOKEN
        ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` }
        : {}),
    },
  });
  return response.json();
}

function normalizeDocUrl(value) {
  const url = new URL(value);
  if (url.protocol !== "https:" || url.hostname !== "clerk.com") {
    throw new Error(`Unexpected Clerk documentation URL: ${value}`);
  }
  if (
    (url.pathname !== "/docs.md" && !url.pathname.startsWith("/docs/")) ||
    !url.pathname.endsWith(".md")
  ) {
    throw new Error(`Unexpected Clerk documentation path: ${value}`);
  }
  url.hash = "";
  url.search = "";
  return url.toString();
}

function parseIndex(text) {
  const linkPattern = /^\s*-\s+\[([^\]]+)]\(([^)]+)\)(?::\s*.*)?$/gm;
  const documents = [];
  const seen = new Map();
  let indexedLinks = 0;
  for (const match of text.matchAll(linkPattern)) {
    indexedLinks += 1;
    const title = match[1].trim();
    const url = normalizeDocUrl(match[2]);
    const previous = seen.get(url);
    if (previous && previous !== title) {
      throw new Error(
        `Clerk index gives ${url} conflicting titles: ${previous} and ${title}`,
      );
    }
    if (!previous) {
      seen.set(url, title);
      documents.push({ title, url });
    }
  }
  const unread = text
    .split(/\r?\n/)
    .filter((line) => line.includes(`](${DOCS_URL.slice(0, -1)}`))
    .filter((line) => !new RegExp(linkPattern.source).test(line));
  if (unread.length > 0) {
    throw new Error(
      `Clerk index has ${unread.length} lines with a documentation link the parser cannot read, first: ${unread[0]}`,
    );
  }
  if (indexedLinks < 2000 || documents.length < 2000) {
    throw new Error(
      `Clerk index yielded only ${indexedLinks} links and ${documents.length} unique documents, expected at least 2000`,
    );
  }
  return documents;
}

function rootFor(document) {
  const pathname = new URL(document.url).pathname;
  if (pathname === "/docs.md") return "docs.md";
  return pathname.replace(/^\/docs\//, "").split("/")[0];
}

function classify(document) {
  const url = new URL(document.url);
  const root = rootFor(document);
  const pathText = url.pathname.toLowerCase();
  const text = `${document.title} ${pathText}`.toLowerCase();
  const segments = pathText.replace(/^\/(docs\/)?/, "").split("/");
  const page = FRAMEWORK_ROOTS.has(root) ? segments.slice(1) : segments;

  if (!KNOWN_ROOTS.has(root)) {
    throw new Error(
      `Unclassified Clerk documentation root: ${root} (${document.url})`,
    );
  }

  // A reference page is filed by its kind, which its folder names. Every other
  // page is filed by topic, from its title and path.
  if (page[0] === "reference") {
    return REFERENCE_FOLDERS.get(page[1]) ?? "sdk-api";
  }
  if (
    root === "getting-started" ||
    root === "templates.md" ||
    /quickstart|quick-start|setup-clerk|install-clerk/.test(text)
  ) {
    return "quickstarts";
  }
  if (
    /billing|subscription|entitlement|pricing-plan|checkout|payment-attempt|feature/.test(
      text,
    )
  ) {
    return "billing";
  }
  if (
    /organization|membership|invitation|enterprise-connection|verified-domain|role|permission|guides\/users\//.test(
      text,
    )
  ) {
    return "users-organizations";
  }
  if (
    /webhook|database|integration|sync(ing)?-user|auth-strategies\/oauth\/|convex|supabase|firebase/.test(
      text,
    )
  ) {
    return "integrations-databases";
  }
  if (
    /security|authorization|protect|restrict|bot|key-rotation|rotate-api-keys|reverification|lockout|enumeration/.test(
      text,
    )
  ) {
    return "security";
  }
  if (
    /sign-in|sign-up|authentication|auth-strategies|session|token|jwt|claim|password|passkey|mfa|multi-factor|machine|m2m|api-key|social-connection|web3/.test(
      text,
    )
  ) {
    return "auth-sessions";
  }
  if (
    /deploy|environment|troubleshoot|testing|test-|playwright|cypress|upgrade|migrat|dashboard|(?:^|[\/-])cli(?:[\/. -]|$)|maintenance|domain|redirect|origin|error/.test(
      text,
    )
  ) {
    return "operations";
  }
  if (pathText.includes("/guides/secure/")) return "security";
  return "concepts-components";
}

function isDeprecated(document) {
  return /deprecated|legacy|previous version|old version/i.test(
    `${document.title} ${document.url}`,
  );
}

function enrichDocuments(documents) {
  return documents
    .map((document) => {
      const root = rootFor(document);
      return {
        title: document.title,
        url: document.url,
        primaryCategory: classify(document),
        framework: FRAMEWORK_ROOTS.has(root) ? root : null,
        deprecated: isDeprecated(document),
      };
    })
    .sort((a, b) => a.url.localeCompare(b.url, "en"));
}

async function inspectRepository(config) {
  const metadata = await fetchJson(
    `https://api.github.com/repos/${config.repo}`,
  );
  const license = metadata.license?.spdx_id ?? null;
  if (!config.expectedLicenses.includes(license)) {
    throw new Error(
      `${config.repo} license changed to ${license ?? "unlicensed"}, expected ${config.expectedLicenses.map((value) => value ?? "unlicensed").join(" or ")}`,
    );
  }
  const commit = await fetchJson(
    `https://api.github.com/repos/${config.repo}/commits/${metadata.default_branch}`,
  );
  return {
    name: config.repo,
    url: metadata.html_url,
    defaultBranch: metadata.default_branch,
    license,
    sha: commit.sha,
  };
}

async function inspectRepositories() {
  const repositories = [];
  for (const config of REPOSITORIES) {
    repositories.push(await inspectRepository(config));
  }
  return repositories.sort((a, b) => a.name.localeCompare(b.name, "en"));
}

async function inspectJavaScriptPackages(repository) {
  const contents = await fetchJson(
    `https://api.github.com/repos/clerk/javascript/contents/packages?ref=${repository.sha}`,
  );
  const directories = contents
    .filter((entry) => entry.type === "dir")
    .map((entry) => entry.name)
    .sort();
  const packages = [];
  for (const directory of directories) {
    const rawUrl = `https://raw.githubusercontent.com/clerk/javascript/${repository.sha}/packages/${directory}/package.json`;
    let manifest;
    try {
      manifest = JSON.parse(
        await fetchText(rawUrl, new Set(["raw.githubusercontent.com"])),
      );
    } catch (error) {
      if (String(error).includes("returned 404")) continue;
      throw error;
    }
    if (
      manifest.private !== true &&
      typeof manifest.name === "string" &&
      manifest.name.startsWith("@clerk/")
    ) {
      packages.push({
        name: manifest.name,
        directory: `packages/${directory}`,
        repository: "clerk/javascript",
      });
    }
  }
  if (packages.length < 15) {
    throw new Error(
      `Found only ${packages.length} @clerk packages in clerk/javascript`,
    );
  }
  return packages.sort((a, b) => a.name.localeCompare(b.name, "en"));
}

function selectAnchor(anchor, documents) {
  const document = documents.find(
    (candidate) => new URL(candidate.url).pathname === anchor.path,
  );
  if (!document) {
    throw new Error(
      `Required Clerk documentation anchor disappeared: ${anchor.key} (${anchor.path})`,
    );
  }
  return document;
}

async function hashAnchors(documents) {
  const anchors = [];
  for (const requirement of REQUIRED_ANCHORS) {
    const document = selectAnchor(requirement, documents);
    const body = await fetchText(document.url, new Set(["clerk.com"]));
    anchors.push({
      key: requirement.key,
      title: document.title,
      url: document.url,
      sha256: sha256(body),
    });
  }
  return anchors.sort((a, b) => a.key.localeCompare(b.key, "en"));
}

function countBy(items, selector) {
  const counts = new Map();
  for (const item of items) {
    const key = selector(item);
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return Object.fromEntries(
    [...counts].sort(([a], [b]) => a.localeCompare(b, "en")),
  );
}

// The path a page has below its framework root. Copies of one page under
// several framework roots share it.
function pagePath(document) {
  const segments = new URL(document.url).pathname
    .replace(/^\/(docs\/)?/, "")
    .split("/");
  return (document.framework ? segments.slice(1) : segments).join("/");
}

// Most framework documents are copies of one page under every framework root.
// A reference lists such a page once, with the roots that carry it.
function groupPages(documents) {
  const pages = new Map();
  for (const document of documents) {
    const key = document.framework
      ? `${pagePath(document)}\n${document.title}`
      : document.url;
    const page = pages.get(key) ?? {
      title: document.title,
      url: document.url,
      path: pagePath(document),
      deprecated: document.deprecated,
      roots: [],
    };
    if (document.framework) page.roots.push(document.framework);
    pages.set(key, page);
  }
  for (const page of pages.values()) {
    page.roots.sort((a, b) => a.localeCompare(b, "en"));
  }
  return [...pages.values()];
}

// Order inside a heading: a folder's overview first, then by path, with
// deprecated pages last.
function comparePages(a, b) {
  const folder = (page) => path.posix.dirname(page.path);
  const overview = (page) => path.posix.basename(page.path) !== "overview.md";
  return (
    a.deprecated - b.deprecated ||
    folder(a).localeCompare(folder(b), "en") ||
    overview(a) - overview(b) ||
    a.path.localeCompare(b.path, "en") ||
    a.title.localeCompare(b.title, "en") ||
    a.url.localeCompare(b.url, "en")
  );
}

// Groups pages under folder headings. A group starts at the first two folders
// of the page path. While it is too long to scan, each next folder with enough
// pages becomes a heading of its own.
function groupByArea(pages, minimum) {
  const foldersOf = (page) => {
    const folder = path.posix.dirname(page.path);
    return folder === "." ? [] : folder.split("/");
  };
  const split = (depth, group) => {
    const area = foldersOf(group[0]).slice(0, depth).join("/");
    const byFolder = new Map();
    for (const page of group) {
      const next = foldersOf(page)[depth];
      if (next) byFolder.set(next, [...(byFolder.get(next) ?? []), page]);
    }
    const promoted =
      group.length > AREA_LIMIT
        ? [...byFolder.values()].filter((next) => next.length >= minimum)
        : [];
    const moved = new Set(promoted.flat());
    const kept = group.filter((page) => !moved.has(page));
    return [
      ...(kept.length > 0 ? [[area, kept]] : []),
      ...promoted.flatMap((next) => split(depth + 1, next)),
    ];
  };
  const start = new Map();
  const legacy = new Map();
  for (const page of pages) {
    const folders = foldersOf(page);
    const at = folders.indexOf("legacy");
    const groups = at === -1 ? start : legacy;
    const key = folders.slice(0, at === -1 ? 2 : at + 1).join("/");
    groups.set(key, [...(groups.get(key) ?? []), page]);
  }
  return [...start.values()]
    .flatMap((group) => split(Math.min(2, foldersOf(group[0]).length), group))
    .concat([...legacy])
    .sort(([a], [b]) => a.localeCompare(b, "en"))
    .map(([area, group]) => [
      area === "" ? TOP_LEVEL_AREA : `\`${area}\``,
      group.sort(comparePages),
    ]);
}

// Groups the helpers each framework SDK owns under that framework's root.
function groupByRoot(documents) {
  const roots = new Map();
  for (const document of documents) {
    const key = document.framework ?? "";
    const page = { ...document, path: pagePath(document), roots: [] };
    roots.set(key, [...(roots.get(key) ?? []), page]);
  }
  return [...roots]
    .sort(([a], [b]) => a.localeCompare(b, "en"))
    .map(([root, group]) => [
      root === "" ? ALL_FRAMEWORKS_AREA : `\`${root}\``,
      group.sort(comparePages),
    ]);
}

function renderRepositoryTable(repositories) {
  const lines = [
    "| Repository | Default branch | License |",
    "| --- | --- | --- |",
  ];
  for (const repository of repositories) {
    lines.push(
      `| [${repository.name}](${repository.url}) | \`${repository.defaultBranch}\` | ${repository.license ?? "No explicit repository license detected"} |`,
    );
  }
  return lines.join("\n");
}

function renderPackageTable(packages) {
  const lines = ["| Package | Source directory |", "| --- | --- |"];
  for (const item of packages) {
    lines.push(
      `| \`${item.name}\` | [\`${item.directory}\`](https://github.com/clerk/javascript/tree/main/${item.directory}) |`,
    );
  }
  return lines.join("\n");
}

function renderPage(page) {
  if (page.roots.length < 2) return `- [${page.title}](${page.url})`;
  const roots = page.roots.map((root) => `\`${root}\``).join(", ");
  return `- ${page.title}: \`<framework>/${page.path}\`. Roots: ${roots}`;
}

// What a reference holds and where a reader finds the rest.
function scopeOf(category) {
  const folders = [...REFERENCE_FOLDERS]
    .filter(([, owner]) => owner === category)
    .map(([folder]) => `\`reference/${folder}\``);
  if (folders.length > 0) {
    return `every Clerk documentation page in ${folders.join(", ")}`;
  }
  return category === "sdk-api"
    ? "what each framework SDK documents for itself, which is every Clerk documentation page in a `reference` folder that no other reference lists"
    : "every Clerk documentation page of this topic outside the `reference` folders";
}

function renderReference(category, documents, repositories, packages) {
  const config = CATEGORY_CONFIG[category];
  const categoryDocuments = documents.filter(
    (document) => document.primaryCategory === category,
  );
  const kindReference = [...REFERENCE_FOLDERS.values()].includes(category);
  const sections = config.byRoot
    ? groupByRoot(categoryDocuments)
    : groupByArea(
        groupPages(categoryDocuments),
        kindReference ? 1 : AREA_MINIMUM,
      );
  const lines = [
    GENERATED_BANNER,
    "",
    `# ${config.title}`,
    "",
    `_Discovery source: [Clerk's language-model documentation index](${INDEX_URL})_`,
    "",
    config.useWhen,
    "",
    "## Operating Guidance",
    "",
    ...config.guidance.map((item) => `- ${item}`),
    "",
  ];

  if (category === "sdk-api") {
    lines.push(
      "## Official Clerk Repositories",
      "",
      renderRepositoryTable(repositories),
      "",
      "## JavaScript Packages",
      "",
      renderPackageTable(packages),
      "",
    );
  }

  const root = `A framework root is the first path segment after \`${DOCS_URL}\`, such as \`nextjs\` or \`expressjs\`.`;
  lines.push(
    SOURCES_HEADING,
    "",
    `This reference lists ${scopeOf(category)}, under headings that are ${config.byRoot ? "framework roots" : "folders of the page path"}. ${config.byRoot || kindReference ? "Pages outside the `reference` folders are in the topic references." : "Pages for a component, hook, object, type, or Backend SDK method are in the four kind references, and pages one framework SDK documents for itself are in the SDK and API reference."}`,
    "",
  );
  if (config.byRoot) {
    lines.push(root, "");
  } else if (
    sections.some(([, pages]) => pages.some((page) => page.roots.length > 1))
  ) {
    lines.push(
      `${root} An entry written as a path that starts with \`<framework>\` is one page that exists under each root named after it, and its URL is \`${DOCS_URL}\` followed by that path with \`<framework>\` replaced by one of those roots.`,
      "",
    );
  }

  for (const [heading, pages] of sections) {
    lines.push(`### ${heading}`, "", ...pages.map(renderPage), "");
  }

  return `${lines.join("\n").trim()}\n`;
}

// Reads the entries of a rendered reference back into titles and URLs, the
// way a reader would.
function readEntries(text) {
  const entries = [];
  const unreadable = [];
  const start = text.indexOf(`${SOURCES_HEADING}\n`);
  if (start === -1) return { entries, unreadable: [SOURCES_HEADING] };
  for (const line of text.slice(start).split("\n")) {
    if (!line.startsWith("- ")) continue;
    const link = line.match(/^- \[(.+)\]\((\S+)\)$/);
    const shared = line.match(/^- (.+): `<framework>\/([^`]+)`\. Roots: (.+)$/);
    if (link) {
      entries.push({ title: link[1], url: link[2] });
    } else if (shared) {
      for (const [, root] of shared[3].matchAll(/`([^`]+)`/g)) {
        entries.push({
          title: shared[1],
          url: `${DOCS_URL}${root}/${shared[2]}`,
        });
      }
    } else {
      unreadable.push(line);
    }
  }
  return { entries, unreadable };
}

// Requires the rendered references to hold the whole index: every document
// once, under its own title, in the reference of its category. A page missing
// from every reference would be unreachable.
function verifyCoverage(outputs, documents) {
  const found = new Map();
  const problems = [];
  for (const [category, config] of Object.entries(CATEGORY_CONFIG)) {
    const { entries, unreadable } = readEntries(
      outputs.get(`references/${config.file}`),
    );
    for (const line of unreadable) {
      problems.push(`${config.file} has an unreadable entry: ${line}`);
    }
    for (const { title, url } of entries) {
      found.set(url, [...(found.get(url) ?? []), { category, title }]);
    }
  }
  const known = new Set(documents.map((document) => document.url));
  for (const document of documents) {
    const entries = found.get(document.url) ?? [];
    if (
      entries.length !== 1 ||
      entries[0].category !== document.primaryCategory ||
      entries[0].title !== document.title
    ) {
      problems.push(
        `${document.url} belongs once in ${document.primaryCategory} as "${document.title}" and is listed as ${JSON.stringify(entries)}`,
      );
    }
  }
  for (const url of found.keys()) {
    if (!known.has(url)) problems.push(`${url} is listed and not indexed`);
  }
  if (problems.length > 0) {
    throw new Error(
      `Generated references do not match the index (${problems.length} problems):\n${problems.slice(0, 20).join("\n")}`,
    );
  }
}

function publicRepository(repository) {
  return {
    name: repository.name,
    url: repository.url,
    defaultBranch: repository.defaultBranch,
    license: repository.license,
  };
}

// What the next run needs beyond the references themselves to report drift.
function renderState(repositories, packages, anchors) {
  return `${JSON.stringify(
    { repositories: repositories.map(publicRepository), packages, anchors },
    null,
    2,
  )}\n`;
}

// The references on disk are the record of the previous run's documents. A
// missing reference or one in an older shape gives no record.
async function readPreviousDocuments() {
  const documents = [];
  for (const [category, config] of Object.entries(CATEGORY_CONFIG)) {
    let text;
    try {
      text = await readFile(path.join(REFERENCES, config.file), "utf8");
    } catch (error) {
      if (error?.code === "ENOENT") return null;
      throw error;
    }
    const { entries, unreadable } = readEntries(text);
    if (unreadable.length > 0) return null;
    for (const entry of entries) {
      documents.push({
        ...entry,
        primaryCategory: category,
        deprecated: isDeprecated(entry),
      });
    }
  }
  return documents;
}

async function readPreviousState() {
  try {
    return JSON.parse(await readFile(path.join(ROOT, STATE_FILE), "utf8"));
  } catch (error) {
    if (error?.code === "ENOENT") return null;
    throw new Error(`Could not read ${STATE_FILE}: ${error.message}`);
  }
}

function mapBy(items, key) {
  return new Map((items ?? []).map((item) => [item[key], item]));
}

function reportSetDiff(label, before, after) {
  const oldSet = new Set(before);
  const newSet = new Set(after);
  const added = [...newSet].filter((value) => !oldSet.has(value)).sort();
  const removed = [...oldSet].filter((value) => !newSet.has(value)).sort();
  if (added.length > 0) {
    console.log(`${label} added (${added.length}):`);
    for (const value of added) console.log(`  + ${value}`);
  }
  if (removed.length > 0) {
    console.log(`${label} removed (${removed.length}):`);
    for (const value of removed) console.log(`  - ${value}`);
  }
}

function reportDocumentDrift(before, after) {
  reportSetDiff(
    "Documents",
    before.map((item) => item.url),
    after.map((item) => item.url),
  );
  const oldDocuments = mapBy(before, "url");
  for (const document of after) {
    const old = oldDocuments.get(document.url);
    if (old && old.primaryCategory !== document.primaryCategory) {
      console.log(
        `Category changed: ${document.url} (${old.primaryCategory} -> ${document.primaryCategory})`,
      );
    }
    if (old && old.deprecated !== document.deprecated) {
      console.log(
        `Deprecation changed: ${document.url} (${old.deprecated} -> ${document.deprecated})`,
      );
    }
  }

  const oldTitleCounts = countBy(before, (item) => item.title);
  const newTitleCounts = countBy(after, (item) => item.title);
  const oldByTitle = mapBy(before, "title");
  for (const document of after) {
    const old = oldByTitle.get(document.title);
    if (
      old &&
      old.url !== document.url &&
      oldTitleCounts[document.title] === 1 &&
      newTitleCounts[document.title] === 1
    ) {
      console.log(
        `Possible move: ${document.title} (${old.url} -> ${document.url})`,
      );
    }
  }
}

function reportDrift(previous, current) {
  if (!previous) {
    console.log("No previous sync state. This is the initial generation.");
    return;
  }
  if (previous.documents) {
    reportDocumentDrift(previous.documents, current.documents);
  } else {
    console.log(
      "The references on disk are missing or in an older shape. Document drift is not reported for this run.",
    );
  }
  reportSetDiff(
    "Packages",
    previous.packages?.map((item) => item.name) ?? [],
    current.packages.map((item) => item.name),
  );
  reportSetDiff(
    "Repositories",
    previous.repositories?.map((item) => item.name) ?? [],
    current.repositories.map((item) => item.name),
  );

  const oldAnchors = mapBy(previous.anchors, "key");
  for (const anchor of current.anchors) {
    const old = oldAnchors.get(anchor.key);
    if (old && old.sha256 !== anchor.sha256) {
      console.log(`Anchor changed: ${anchor.key} (${anchor.url})`);
    }
  }

  const oldRepositories = mapBy(previous.repositories, "name");
  for (const repository of current.repositories) {
    const old = oldRepositories.get(repository.name);
    if (old && old.license !== repository.license) {
      console.log(
        `Repository license changed: ${repository.name} (${old.license ?? "unlicensed"} -> ${repository.license ?? "unlicensed"})`,
      );
    }
  }
}

async function writeOutputs(outputs, checkOnly) {
  const changed = [];
  for (const [relativePath, content] of outputs) {
    const destination = path.join(ROOT, relativePath);
    let existing = null;
    try {
      existing = await readFile(destination, "utf8");
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
    if (existing !== content) changed.push(relativePath);
  }

  const stale = [];
  const present = await readdir(REFERENCES, { withFileTypes: true }).catch(
    () => [],
  );
  for (const entry of present) {
    const relativePath = `references/${entry.name}`;
    if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
    if (outputs.has(relativePath)) continue;
    const content = await readFile(path.join(ROOT, relativePath), "utf8");
    if (!content.startsWith(GENERATED_BANNER)) {
      throw new Error(
        `${relativePath} is not generated by this script. Move or remove it by hand.`,
      );
    }
    stale.push(relativePath);
  }

  if (checkOnly) {
    if (changed.length > 0 || stale.length > 0) {
      for (const file of changed) console.error(`out of date: ${file}`);
      for (const file of stale) console.error(`stale: ${file}`);
      process.exitCode = 1;
    } else {
      console.log("Generated Clerk references are current.");
    }
    return;
  }

  await mkdir(REFERENCES, { recursive: true });
  for (const [relativePath, content] of outputs) {
    await writeFile(path.join(ROOT, relativePath), content, "utf8");
    console.log(`wrote ${relativePath}`);
  }
  for (const relativePath of stale) {
    await rm(path.join(ROOT, relativePath));
    console.log(`removed ${relativePath}`);
  }
}

async function exportOutputs(repositories, indexHash) {
  if (!process.env.GITHUB_OUTPUT) return;
  const entries = [
    ["llms_sha256", indexHash],
    ...repositories.map((repository) => [
      `${repository.name.replace(/[^a-z0-9]+/gi, "_").toLowerCase()}_sha`,
      repository.sha,
    ]),
  ];
  await appendFile(
    process.env.GITHUB_OUTPUT,
    entries.map(([key, value]) => `${key}=${value}`).join("\n") + "\n",
  );
}

async function main() {
  const args = new Set(process.argv.slice(2));
  if (args.has("--help") || args.has("-h")) {
    printHelp();
    return;
  }
  const allowed = new Set(["--check"]);
  for (const argument of args) {
    if (!allowed.has(argument))
      throw new Error(`Unknown argument: ${argument}`);
  }
  const checkOnly = args.has("--check");

  const indexText = await fetchText(INDEX_URL, new Set(["clerk.com"]));
  const parsed = parseIndex(indexText);
  const documents = enrichDocuments(parsed);
  const roots = new Set(documents.map(rootFor));
  const unknownRoots = [...roots].filter((root) => !KNOWN_ROOTS.has(root));
  if (unknownRoots.length > 0) {
    throw new Error(
      `Unknown Clerk documentation roots: ${unknownRoots.join(", ")}`,
    );
  }

  const repositories = await inspectRepositories();
  const javascript = repositories.find(
    (repository) => repository.name === "clerk/javascript",
  );
  const packages = await inspectJavaScriptPackages(javascript);
  const anchors = await hashAnchors(documents);
  const indexHash = sha256(indexText);

  const publicIndex = {
    repositories: repositories.map(publicRepository),
    packages,
    anchors,
    documents,
  };
  const state = await readPreviousState();
  reportDrift(
    state && { ...state, documents: await readPreviousDocuments() },
    publicIndex,
  );

  const outputs = new Map();
  for (const category of Object.keys(CATEGORY_CONFIG)) {
    const file = CATEGORY_CONFIG[category].file;
    outputs.set(
      `references/${file}`,
      renderReference(category, documents, repositories, packages),
    );
  }
  verifyCoverage(outputs, documents);
  outputs.set(STATE_FILE, renderState(repositories, packages, anchors));

  await writeOutputs(outputs, checkOnly);
  console.log(
    `indexed ${documents.length} Clerk documents, ${packages.length} JavaScript packages, and ${repositories.length} repositories`,
  );
  for (const repository of repositories) {
    console.log(`upstream ${repository.name} @ ${repository.sha}`);
  }
  console.log(`upstream llms.txt sha256 ${indexHash}`);
  await exportOutputs(repositories, indexHash);
}

main().catch((error) => {
  console.error(error.stack ?? error.message ?? String(error));
  process.exit(1);
});
